nodemon.json, package.json, yarn.lock
Closes #4 
Add nodemon dependency + nodemon configuration
=> Add nodemon

.eslintrc, .prettierrc, components/Game/index.js, package.json, pages/_app.js, pages/index.js, server/cards.js, server/game.js, server/index.js, server/player.js, server/players.js, yarn.lock
Closes #10 
This PR also this syntax issue and some mispelt variables.
=> Add eslint & pettier with simple light config

server/constants.js, server/game.js, server/index.js, server/players.js
Close #8, #7 
This PR limites the number of simultaneous ongoing game.  
It also also player to reconnect to a game and rejects new player after the game is ready
=> Allow player to reconnect to a game

components/Game/index.js, server/constants.js, server/game.js, server/index.js, server/player.js, server/players.js
There is no need to hide cards in the client side, so this PR removes data masking and do the card watching on the frontend side.
It also fixes giving a card to others players.
=> Do card watching on the front end side

.babelrc, components/Card/index.js, components/Game/index.js, components/PlayingCard/index.js, components/layout/Column/index.js, components/layout/Flex/helpers.js, components/layout/Flex/index.js, components/layout/Row/index.js, components/layout/index.js, components/text/Body/index.js, components/text/Subheading/index.js, components/text/index.js, components/theme.js, package.json, pages/_document.js, yarn.lock
This PR setups styled-components and adds some basic components.
Closes #18
=> Styled components

components/Game/index.js, components/PlayingCard/index.js, server/game.js, server/index.js, server/player.js
This PR adds the Jack & Joker card action.
Closes #2 
Closes #3
=> Add jacks & joker card action

components/Game/DiscardPile/index.js, components/Game/PickedCard/index.js, components/Game/PlayerCards/index.js, components/Game/index.js, components/PlayingCard/index.js, components/text/Heading/index.js, components/text/Subheading/index.js, components/text/index.js
This PR splits the Game component into smaller components. This should make the implementation of the game interface easier in the future.
It also fixes a bug where `unfoldedCards` were not scoped by player.
=> Split Game in smaller components

components/Game/index.js, server/game.js, server/index.js, server/player.js, server/players.js
This PR fixes the score calculation at this end of the game. 
It also allows a player to finish while giving his last card.
It also fixes the reset of the game/players data at the end of the game.
Finally, a little fix about selecting card on the joker action.
=> Fix end of game

server/cards.js, server/game.js
=> Remove joker for game with less than 3 players

components/Game/index.js
Close #27 
There was an issue when a player that has a tmpCard, throw someone else's card, he looses his tmpCard. (But only on the client)
=> Remove tmpCard from state, use game data instead

components/Game/PlayerCards/_styled.js, components/Game/PlayerCards/index.js, components/Game/index.js, components/theme.js, server/game.js, server/index.js
This PR adds a simple feedbacks over the card that someone is looking the card.
This PR fixes also a bug created  when removing the joker for game with less than 3 peoples.
=> Add feedback to players that someone is looking a card

components/Game/PlayerCards/index.js, components/Game/index.js, server/game.js, server/index.js
This PR fixes an issue with the "give" `nextAction` and also adds a reveal of player's cards when the game end.
=> Reveal players cards at the end of the game

components/Game/index.js, hooks/GameProvider.js, server/game.js, server/index.js, server/player.js, server/players.js
Close #5 
Close #41
This PR adds the caracole gameplay. 
It also fixes 2 bugs:
- The game should not end when someone steals the last card of a player;
- The card's action after someone throws other player's card was wrongly attributed to the card player's instead of the one who throws it.
=> Add caracole gameplay

components/Game/DiscardPile/_styled.js, components/Game/DiscardPile/index.js, components/Game/PickedCard/_styled.js, components/Game/PickedCard/index.js, components/Game/Scoreboard/_styled.js, components/Game/Scoreboard/index.js, components/Game/_styled.js, components/Game/index.js, components/PlayingCard/index.js, components/text/Link/index.js, components/text/index.js, components/theme.js
This PR updates the layout of the draw pile and add a real scoreboard.
=> Add Scoreboard and update board

server/cards.js
This PR adds an unique ID to each card.
=> Add unique id to card

components/Game/DiscardPile/_styled.js, components/Game/DiscardPile/index.js, components/Game/index.js, hooks/useCardActions.js, server/game.js, server/index.js
This PR adds the reveal of a wrong card thrown.
=> Add wrong card thrown

components/Game/PlayerCards/index.js, components/Game/Scoreboard/index.js, hooks/useCardActions.js, server/cards.js, server/game.js, server/player.js
This PR adds metadata for each card.
Example:
```
metadata: {
isBeingWatched: false,
playerId: null,
cardSpot: `player${player.id}_${cards.length}`
}
```
=> Add metadata for each cards

components/AnimatedPlayingCard/_styled.js, components/AnimatedPlayingCard/helpers.js, components/AnimatedPlayingCard/index.js, components/CardSpot/index.js, components/Game/PlayerCards/_styled.js, components/Game/PlayerCards/index.js, components/Game/Players/BottomPlayer/_styled.js, components/Game/Players/BottomPlayer/index.js, components/Game/Players/LeftPlayer/_styled.js, components/Game/Players/LeftPlayer/index.js, components/Game/Players/RightPlayer/_styled.js, components/Game/Players/RightPlayer/index.js, components/Game/Players/TopPlayer/_styled.js, components/Game/Players/TopPlayer/index.js, components/Game/Scoreboard/index.js, components/Game/index.js, components/PlayingCard/_styled.js, components/PlayingCard/index.js, components/theme.js, hooks/GameProvider.js, hooks/useCardActions.js
=> Display cards as square and display players around the draw pile

.gitignore, Makefile, README.md, deploy.sample.json, package.json, server/index.js, yarn.lock
This PR adds an easy and simple deploy process using PM2.
=> Add simple deploy process

components/PlayingCard/_styled.js, components/PlayingCard/index.js, public/assets/eye.svg
Close #64
This PR adds a feedback that a card is being watched.
=> Add eye over card being watched

components/Button/index.js, components/Game/Scoreboard/index.js, components/theme.js, hooks/useGame.js, server/game.js, server/index.js, server/player.js, server/players.js
This PR adds a reset button that only the game creator can use to reset the game along with the scores.
=> Add button to reset the game (with scores)

server/game.js
Fix #58 
Required #70 
This PR updates the player who have picked Failed card to be the owner of the card.
=> Failed card should be get back by its own player

components/PlayingCard/index.js
Close #66
This PR reveals all the players cards when the game is over.
=> Reveal cards of players when game is over

server/player.js
This PR fixes a bug where the players cards spots mismatched the cards list of the game. 
(Before, some players cards where still set as 'picked-card')
=> Sync players cards with game cards list

server/game.js, server/index.js
Fix #73
This PR fixes the reset of the draw pile when it runs of card.
=> Fix reset of the draw pile when it runs out of card

components/AnimatedPlayingCard/index.js, components/Game/index.js, components/LoginForm/index.js, components/PlayingCard/index.js, server/index.js
Close #61 
Close #77
This PR also slows down the animation card and remove the ability to throw a unfolded card to avoid Queen discovering bug. It also adds a new five player layout.
=> Add Game name in the URL & five players layout
